USE DATABASE DEV_DB;
USE SCHEMA DEV_SCH;


CREATE TABLE BAGONG_TBL_SA_DEV(
PANGALAN VARCHAR,
APELYIDO VARCHAR,
SCHOOL VARCHAR
);


INSERT INTO BAGONG_TBL_SA_DEV
VALUES('LEVI','ACKERMAN','TAGA KYUSI');