name: Run Python Script

on:
  issues:
    types: [opened]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Uncomment the following step if you have a requirements.txt file
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Run Python script
      run: |
        python .github/workflows/main.py
      env:
        DB_SFNAME: ${{ github.event.issue.body.dbSfname }}
        SCHEMA_SFNAME: ${{ github.event.issue.body.schemaSfname }}