name: Run Python Script

on:
  issues:
    types: [opened]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Issue Body
        run: |
          echo "Issue Body: ${{ github.event.issue.body }}"

      - name: Extract Feature Branch Name
        id: extract_branch
        run: |
          FEATURE_BRANCH=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=Feature Branch: ).*' | tr -d '\r')
          echo "Extracted branch: $FEATURE_BRANCH"
          echo "FEATURE_BRANCH=$FEATURE_BRANCH" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.FEATURE_BRANCH }}

      - name: Print current branch
        run: |
          echo "Current branch: $(git branch --show-current)"

      - name: Run Python script
        run: |
          python .github/workflows/main.py
        env:
          DB_SFNAME: ${{ github.event.issue.body.dbSfname }}
          SCHEMA_SFNAME: ${{ github.event.issue.body.schemaSfname }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add snowflake/conversion
          git commit -m "Rename and update SQL files"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git ${{ env.FEATURE_BRANCH }}
