name: Run Python Script

on:
  issues:
    types: [opened]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false # This ensures the credentials are not persisted

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout feature branch
      run: |
        git checkout ${{ github.event.issue.body.featureBranch }}

    # Uncomment the following step if you have a requirements.txt file
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Run Python script
      run: |
        python .github/workflows/main.py
      env:
        DB_SFNAME: ${{ github.event.issue.body.dbSfname }}
        SCHEMA_SFNAME: ${{ github.event.issue.body.schemaSfname }}
        FILE_LOC: ${{ github.event.issue.body.fileLoc }}

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add snowflake/conversion
        git commit -m "Rename and update SQL files"

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.event.issue.body.featureBranch }}